services:
  postgres-ml:
    image: postgres:16
    container_name: ml-service-db
    environment:
      POSTGRES_USER: ${DB_USER_ML_SERVICE}
      POSTGRES_PASSWORD: ${DB_PASSWORD_ML_SERVICE}
      POSTGRES_DB: ${DB_NAME_ML_SERVICE}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER_ML_SERVICE}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ml_postgres_data: